# Docker Compose configuration for mobile app development
# Use: docker-compose -f docker-compose.mobile.yml up

services:
  # Mobile development requires backend and database from main academy-admin
  # Run backend services: cd ../academy-admin && docker-compose up db backend
  
  # Instructor Mobile App
  instructor-mobile:
    build:
      context: ./academy-instructors-app
      dockerfile: Dockerfile.dev
    ports:
      - "19006:19006"  # Expo Metro bundler
      - "8081:8081"    # Metro dev server
    volumes:
      - ./academy-instructors-app:/app
      - instructor_node_modules:/app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - API_BASE_URL=http://host.docker.internal:8000/api/v1
      - WS_BASE_URL=ws://host.docker.internal:8000/ws
      - APP_ENV=development
      - EXPO_CLI_TELEMETRY_DISABLED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
    command: >
      sh -c "
        echo '🚀 Starting Instructor Mobile App Development...' &&
        echo '📦 Installing dependencies...' &&
        npm install &&
        echo '⚡ Starting Expo development server...' &&
        npx expo start --clear --dev-client --lan
      "

  # Student Mobile App
  student-mobile:
    build:
      context: ./academy-students-app
      dockerfile: Dockerfile.dev
    ports:
      - "19007:19006"  # Expo Metro bundler (different port)
      - "8082:8081"    # Metro dev server (different port)
    volumes:
      - ./academy-students-app:/app
      - student_node_modules:/app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - API_BASE_URL=http://host.docker.internal:8000/api/v1
      - WS_BASE_URL=ws://host.docker.internal:8000/ws
      - APP_ENV=development
      - EXPO_CLI_TELEMETRY_DISABLED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
    command: >
      sh -c "
        echo '🚀 Starting Student Mobile App Development...' &&
        echo '📦 Installing dependencies...' &&
        npm install &&
        echo '⚡ Starting Expo development server...' &&
        npx expo start --clear --dev-client --lan
      "


volumes:
  instructor_node_modules:
  student_node_modules: