name: Bug Report
description: File a bug report for Academy Mobile Apps
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: app
    attributes:
      label: Which app is affected?
      description: Select the app where you encountered the bug
      options:
        - Academy Instructors App
        - Academy Students App
        - Shared Components/Services
        - Both Apps
        - Not Sure
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - iOS
        - Android
        - Web
        - All Platforms
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: textarea
    id: device-info
    attributes:
      label: Device Information
      description: Please provide device details
      placeholder: |
        - Device: [e.g. iPhone 14, Samsung Galaxy S23]
        - OS Version: [e.g. iOS 16.1, Android 13]
        - App Version: [e.g. 2.0.0]
        - Expo Client Version: [if using Expo Go]

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here